plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinAndroid)
    alias(libs.plugins.kotlinCompose)
}

val chromiumAar = file("libs/cobalt-content.aar")
val hasChromium = chromiumAar.exists()

android {
    namespace = "app.auriel.cobalt"
    // 36, to match Chromium: its own APK is built targetSdk 36, and the
    // androidx.core the AAR's Java expects requires compiling against 36.
    compileSdk = 36

    defaultConfig {
        applicationId = "app.auriel.cobalt"
        // 29, not 24, because that is Chromium's floor: chrome_public_apk is
        // built with minSdkVersion 29 and the embedded Java assumes it. Keeping
        // 24 here would let the app install on devices the engine cannot run
        // on, which is a crash rather than a degraded experience.
        //
        // org.chromium.build.BuildConfig.MIN_SDK_VERSION must match this.
        minSdk = 29
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"

        // Which Application class the manifest names.
        //
        // Chromium needs two globals set before the first Activity exists, and
        // an Application is the only place early enough -- see
        // content/CobaltApplication.kt. But that class imports org.chromium and
        // is excluded from the build when the AAR is absent, and a manifest
        // naming a class that is not in the APK is a crash on launch, not a
        // build error. So the manifest asks for it by placeholder and the two
        // configurations stay consistent.
        manifestPlaceholders["applicationClass"] =
            if (hasChromium) "app.auriel.cobalt.content.CobaltApplication"
            else "android.app.Application"
    }

    buildFeatures {
        compose = true
    }

    // The Chromium AAR carries one ABI, because that is what the Chromium
    // checkout is configured to build (target_cpu = "arm64" in args.gn). Saying
    // so explicitly keeps the APK honest rather than letting it claim ABIs it
    // has no engine for.
    defaultConfig {
        ndk { abiFilters += "arm64-v8a" }
    }

    // Chromium's runtime assets live in their own source set, written by
    // tools/build/export-aar.sh. Keeping them out of src/main/assets means the
    // export can clear its own destination without touching files this
    // repository owns, which is a mistake this made once already.
    // Only with the AAR: these directories are generated from it, and left over
    // from an earlier export they reference classes the build no longer has.
    if (hasChromium) sourceSets {
        getByName("main") {
            assets.srcDir("src/chromium/assets")
            // GEN_JNI and J.N, generated by Chromium and copied in by
            // export-aar.sh. They must be compiled into the APK exactly once,
            // which is why they cannot ride in the AAR.
            java.srcDir("src/chromium/java")
            // One R class per Chromium resource package, forwarding to the
            // app's R. dist_aar strips Chromium's own, and shipping them
            // verbatim would carry ids from the wrong aapt2 link -- see
            // tools/build/generate-chromium-r.py.
            java.srcDir("src/chromium/r")
        }
    }

    androidResources {
        // Chromium reads several assets by file descriptor, through
        // base::android::OpenApkAsset, which only works on an asset stored
        // UNCOMPRESSED in the APK. AGP compresses assets by default, and
        // Chromium's failure is immediate and fatal:
        //
        //   [ERROR:base/i18n/icu_util.cc:223] Invalid file descriptor to ICU
        //   data received.
        //   [FATAL:base/i18n/icu_util.cc:297] Check failed: result.
        //
        // This is the same constraint the bundled uBlock Origin CRX hit on the
        // Chromium side, where the fix was disable_compression = true on the
        // android_assets target -- see docs/ublock-bundling.md. Same rule, same
        // reason, different build system.
        //
        //   dat   icudtl.dat
        //   pak   resources.pak, chrome_100_percent.pak, locales/*.pak
        //   bin   v8 snapshot data
        //   crx   the bundled extension
        noCompress += setOf("dat", "pak", "bin", "crx")
    }

    packaging {
        resources {
            // The AAR's classes.jar still carries a few root-level metadata
            // files from libraries the app also has, and two copies of a
            // packaged resource is a hard failure:
            //
            //   2 files found with path 'DebugProbesKt.bin'
            //
            // None of these is used at runtime -- they are debugger and build
            // metadata -- so dropping the duplicate is the whole fix.
            excludes += setOf(
                "DebugProbesKt.bin",
                "META-INF/*.version",
                "META-INF/*.kotlin_module",
                "META-INF/versions/**",
            )
        }

        jniLibs {
            // libchrome.so is 205 MB and must be mapped out of the APK rather
            // than extracted to disk at install time; see docs/apk-size.md,
            // where the same setting on the Chromium build is blocked by the
            // crashpad handler. Nothing here has that problem.
            useLegacyPackaging = false
        }
    }

    // Release signing, from a keystore named in ~/.gradle/gradle.properties
    // (cobalt.keystore, cobalt.keystore.password, cobalt.key.alias,
    // cobalt.key.password) and never from this repository. There is no project
    // release key yet: whoever holds it controls every future update, so
    // creating one is the maintainer's decision, not a build script's. Until
    // it exists a release build is signed with the debug key, which installs
    // and runs but is not an update path anyone should rely on.
    val releaseKeystore = (findProperty("cobalt.keystore") as String?)?.let(::file)
    signingConfigs {
        if (releaseKeystore != null) create("release") {
            storeFile = releaseKeystore
            storePassword = findProperty("cobalt.keystore.password") as String?
            keyAlias = findProperty("cobalt.key.alias") as String?
            keyPassword = findProperty("cobalt.key.password") as String?
        }
    }

    buildTypes {
        debug {
            // The nightly channel installs alongside stable rather than over it,
            // so a bug report can never be ambiguous about which build it came
            // from. See docs/branching.md.
            applicationIdSuffix = ".nightly"
            versionNameSuffix = "-nightly"
            resValue("string", "app_name", "Cobalt Nightly")
        }
        release {
            isMinifyEnabled = false
            resValue("string", "app_name", "Cobalt")
            signingConfig = signingConfigs.findByName("release") ?: signingConfigs.getByName("debug")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

// The Chromium engine, copied in by tools/build/export-aar.sh.
//
// Optional on purpose. The AAR is ~260 MB, gitignored, and reproducible from
// the Chromium checkout in a minute -- so a fresh clone will not have it, and a
// fresh clone must still build. Without it the app runs on the 0.1.0 document
// engine, which is exactly what DocumentEngine exists for.
// Without the AAR, app/.../content/ cannot compile: every file in it imports
// org.chromium. This module is meant to build either way -- a fresh clone has
// no AAR and falls back to the 0.1.0 document engine -- so those sources are
// dropped from the compilation rather than the property being given up.
//
// Filtered on the compile task rather than in the `sourceSets` block: AGP's
// AndroidSourceSet has no Kotlin-DSL accessor for excluding from the Kotlin
// source set, while KotlinCompile is an ordinary Gradle SourceTask and takes
// patterns relative to the source roots.
if (!hasChromium) {
    tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
        exclude("app/auriel/cobalt/content/**")
    }
}

if (hasChromium) {
    // com.google.guava:listenablefuture:1.0 is an empty stub artifact. It
    // exists only so Maven can resolve a version conflict, and it declares
    // ListenableFuture without implementing anything. androidx pulls it in
    // transitively, and the AAR carries the real Guava, so the two collide:
    //
    //   Duplicate class com.google.common.util.concurrent.ListenableFuture
    //
    // Dropping the stub is the standard resolution and the right one here --
    // the real class is present, from Chromium.
    configurations.all {
        exclude(group = "com.google.guava", module = "listenablefuture")
    }
}

dependencies {
    if (hasChromium) {
        implementation(files(chromiumAar))

        // Chromium's Java was compiled against androidx.core 1.17.0-SNAPSHOT --
        // third_party/androidx ships a CI snapshot, not a Maven release -- and
        // the AAR excludes androidx classes so the app supplies them instead.
        // A version older than Chromium expects is a runtime failure, not a
        // build one:
        //
        //   java.lang.NoSuchMethodError: No static method isAtLeastB()Z in
        //   class Landroidx/core/os/BuildCompat;
        //
        // So the app's androidx.core is forced up to meet it. This is the skew
        // predicted when androidx was excluded from the AAR, arriving exactly
        // where it was predicted to: at runtime.
        implementation("androidx.core:core:1.16.0")

        // AppCompat, for the same reason and found the same way.
        //
        // Cobalt's own interface is Compose and wants nothing from AppCompat,
        // so this looks like a dependency the app does not need. It is not the
        // app that needs it: Chrome's Java does. `ChromeActivity` extends
        // `AsyncInitializationActivity` extends `ChromeBaseAppCompatActivity`
        // extends `androidx.appcompat.app.AppCompatActivity`, and Chromium's
        // C++ resolves `ChromeActivity` by name during browser startup, so the
        // whole chain has to load:
        //
        //   ClassNotFoundException: org.chromium.chrome.browser.app.ChromeActivity
        //   Caused by: ... AsyncInitializationActivity
        //   Caused by: ... ChromeBaseAppCompatActivity
        //   Caused by: Didn't find class androidx.appcompat.app.AppCompatActivity
        //
        // Only under `hasChromium`: without the AAR nothing references it, and
        // the document-engine build should not carry a library it never loads.
        implementation("androidx.appcompat:appcompat:1.7.0")
    }

    implementation(project(":modules:core"))
    implementation(project(":modules:engine"))

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.foundation)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.extended)
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.tooling.preview)
    debugImplementation(libs.compose.ui.tooling)

    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(libs.kotlin.test)
}
